# The URL the site will be built for
base_url = "https://MinLee0210.github.io"
theme = "BelResume"
build_search_index = true

[markdown]
highlight_code = true

[extra]

blog_name = "MinLee0210"
config_js = "config.js"
custom_css = "style.css"
