name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or master, depending on your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zola
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GITHUB_TOKEN as an environment variable
        with:
          args: --build-dir public  # Use args to specify the build directory